Dev
MadeOfSt0ne/go-first-floor-sprint-five pull request #1
Opened 2023-11-23 20:54 UTC by MadeOfSt0ne

2023-11-23 21:40 UTC, just-musha requested changes
Спасибо за быстрый пул реквест.

Есть небольшие правки по коду. Главное что предлагаю поправить - это метод TrainingInfo для Swimming. Остальные правки не критичны.

Здоровое что есть проверки Duration на 0 перед делением. Жду правки, чтобы принять работу.

2023-11-23 21:40 UTC, just-musha commented on main.go
> +	return s.Training.TrainingInfo()
Вот здесь важный момент: в running/walking у нас скорость рассчитывается по "базовой" формуле, которая есть в Training. В случае с плаванием, скорость вычисляется в конкретной реализации meanSpeed для Swimming. Здесь тебе нужно завести структуру InfoMessage и там явно вызвать метод s.meanSpeed() для Swimming, и вернуть эту структуру

2023-11-23 21:40 UTC, just-musha commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (speed/w.Height/CmInM)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Здесь можно убрать внешние скобки, они ни на что не влияют

2023-11-23 21:40 UTC, just-musha commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (speed/w.Height/CmInM)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Стоит внимательно проверить формулу, аккуратно все приведения к другим единицам измерения. Должно получиться 947.82, на данных из функции main.

2023-11-23 21:40 UTC, just-musha commented on main.go
> +	return ((CaloriesMeanSpeedMultiplier * speed * CaloriesMeanSpeedShift) * r.Weight / MInKm * r.Duration.Hours() * MinInHours)
Здесь тоже можно убрать внешние скобки

2023-11-23 21:40 UTC, just-musha commented on main.go
> +	return ((CaloriesMeanSpeedMultiplier * speed * CaloriesMeanSpeedShift) * r.Weight / MInKm * r.Duration.Hours() * MinInHours)
Формулу стоит ещё раз проверить. Где-то есть ошибка. Функция должна вернуть 302.91

2023-11-23 22:02 UTC, MadeOfSt0ne commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (speed/w.Height/CmInM)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
убрал скобки

2023-11-23 22:02 UTC, MadeOfSt0ne commented on main.go
> +	return ((CaloriesMeanSpeedMultiplier * speed * CaloriesMeanSpeedShift) * r.Weight / MInKm * r.Duration.Hours() * MinInHours)
убрал скобки

2023-11-23 22:06 UTC, MadeOfSt0ne commented on main.go
> +	return s.Training.TrainingInfo()
а я уж надеялся, что если я переопределяю метод meanSpeed для плавания, то он и будет вызываться для trainingInfo. облом =( Добавил в метод явные вызовы

2023-11-23 22:29 UTC, MadeOfSt0ne commented on main.go
> +	return ((CaloriesMeanSpeedMultiplier * speed * CaloriesMeanSpeedShift) * r.Weight / MInKm * r.Duration.Hours() * MinInHours)
ошибку исправил

2023-11-23 22:29 UTC, MadeOfSt0ne commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (speed/w.Height/CmInM)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
ошибку исправил

2023-11-24 07:01 UTC, just-musha approved these changes
Спасибо! Все хорошо, работа принята.

2023-11-24 18:22 UTC, merged